# 03 - SQLite Load

This notebook loads the processed UK electricity demand dataset into a local SQLite database.

The workflow includes:

- Loading the processed CSV file
- Creating a local SQLite database
- Writing the dataset to a database table
- Running basic SQL checks

In [2]:
%reset -f

import pandas as pd
import sqlite3
from pathlib import Path

## Load Processed Dataset

In [5]:
processed_file = Path("../Data/Processed/combined_energy_demand.csv")
df = pd.read_csv(processed_file)
df.head()

,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,NON_BM_STOR,...,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,SCOTTISH_TRANSFER,DATETIME
0,2021-01-01,1,28354,28969,26130,1158,6527,0,13471,0,...,0,215,203,999,0,0,0,0,0.0,2021-01-01 00:00:00
1,2021-01-01,2,28501,29114,26281,1208,6527,0,13471,0,...,0,359,203,999,0,0,0,0,0.0,2021-01-01 00:30:00
2,2021-01-01,3,27759,28376,25557,1202,6527,0,13471,0,...,0,362,202,999,0,0,0,0,0.0,2021-01-01 01:00:00
3,2021-01-01,4,26912,27749,24792,1226,6527,0,13471,0,...,0,361,203,1000,0,0,0,0,0.0,2021-01-01 01:30:00
4,2021-01-01,5,26004,27178,23933,1193,6527,0,13471,0,...,0,304,203,1000,0,0,0,0,0.0,2021-01-01 02:00:00

## Create SQLite Database Connection

In [8]:
database_path = Path("../Data/Processed/energy_pipeline.db")
connection = sqlite3.connect(database_path)

print("SQLite database connection created successfully.")

SQLite database connection created successfully.

## Load Dataset into SQLite Table

In [11]:
df.to_sql(
    "energy_demand",
    connection,
    if_exists="replace",
    index=False
)

print("Dataset loaded into SQLite successfully.")

Dataset loaded into SQLite successfully.

## Validate SQLite Table Load

In [14]:
query = """
SELECT COUNT(*) AS total_rows
FROM energy_demand
"""

row_count = pd.read_sql_query(query, connection)
row_count

   total_rows
0       89472

## Example SQL Aggregation Query

In [17]:
query = """
SELECT
    SUBSTR(SETTLEMENT_DATE, 1, 4) AS year,
    ROUND(AVG(ENGLAND_WALES_DEMAND), 2) AS average_demand
FROM energy_demand
GROUP BY year
ORDER BY year
"""

average_demand = pd.read_sql_query(query, connection)
average_demand

   year  average_demand
0  2021        25900.07
1  2022        24415.46
2  2023        23857.90
3  2024        24161.06
4  2025        23996.22
5  2026        30214.68

## SQLite Load Summary

The processed UK electricity demand dataset was successfully loaded into a local SQLite database.

Validation confirmed:

- Successful database connection
- Successful table creation
- Correct row count after loading
- Successful execution of SQL aggregation queries

The dataset is now available for downstream querying and cloud upload operations.