# 04 - BigQuery Upload

This notebook uploads the processed UK electricity demand dataset to Google BigQuery.

The workflow includes:

- Loading the processed dataset
- Authenticating with Google Cloud
- Connecting to BigQuery
- Uploading the dataset to a BigQuery table
- Validating the cloud upload

In [17]:
%reset -f

import pandas as pd
from pathlib import Path
from google.cloud import bigquery

## Authenticate with Google Cloud

In [20]:
credentials_path = Path("../Credentials/chrome-energy-496120-j4-299aaa8130ba.json")
client = bigquery.Client.from_service_account_json(credentials_path)

print("BigQuery client created successfully.")

BigQuery client created successfully.

## Load Processed Dataset

In [23]:
processed_file = Path("../Data/Processed/combined_energy_demand.csv")
df = pd.read_csv(processed_file)
df.head()

,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,NON_BM_STOR,...,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,SCOTTISH_TRANSFER,DATETIME
0,2021-01-01,1,28354,28969,26130,1158,6527,0,13471,0,...,0,215,203,999,0,0,0,0,0.0,2021-01-01 00:00:00
1,2021-01-01,2,28501,29114,26281,1208,6527,0,13471,0,...,0,359,203,999,0,0,0,0,0.0,2021-01-01 00:30:00
2,2021-01-01,3,27759,28376,25557,1202,6527,0,13471,0,...,0,362,202,999,0,0,0,0,0.0,2021-01-01 01:00:00
3,2021-01-01,4,26912,27749,24792,1226,6527,0,13471,0,...,0,361,203,1000,0,0,0,0,0.0,2021-01-01 01:30:00
4,2021-01-01,5,26004,27178,23933,1193,6527,0,13471,0,...,0,304,203,1000,0,0,0,0,0.0,2021-01-01 02:00:00

## Configure BigQuery Table

In [26]:
table_id = ("chrome-energy-496120-j4.energy_data.energy_demand")
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE"
)

print("BigQuery table configuration created.")

BigQuery table configuration created.

## Upload Dataset to BigQuery

In [29]:
load_job = client.load_table_from_dataframe(
    df,
    table_id,
    job_config=job_config
)

load_job.result()
print("Dataset uploaded to BigQuery successfully.")

C:\Users\david\anaconda3\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

Dataset uploaded to BigQuery successfully.

## Validate BigQuery Upload

In [32]:
query = """
SELECT COUNT(*) AS total_rows
FROM `chrome-energy-496120-j4.energy_data.energy_demand`
"""

query_result = client.query(query).to_dataframe()
query_result

C:\Users\david\anaconda3\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

   total_rows
0       89472

## BigQuery Upload Summary

The processed UK electricity demand dataset was successfully uploaded to Google BigQuery.

Validation confirmed:

- Successful authentication with Google Cloud
- Successful upload to BigQuery
- Successful table creation
- Correct row count after upload
- Successful SQL validation query execution

The cloud data warehouse stage of the pipeline is complete.